### PR TITLE
Apply bug fixes/suggestions

### LINKED ISSUE #7912: Apply bug fixes/suggestions from 9/25/2020

### PR DESCRIPTION
**Pull request by jtquach1**
Resolves [7912](https://github.com/cBioPortal/cbioportal/issues/7912).

- Changed "Waypoints" to "cBioPortal Instances"
- Changed search bar filter to only display table rows with that query and not its siblings from the same parent
- Added toggle to filter map based on the search query
- Merged "Filter by visibility" checkbox into "Sync map and table"
  - Only Markers that match the searchbar query will display on the map

### Before
map_sync_before

### After
map_sync_after

### CODE REVIEW

**Comment by jtquach1** [comment]
Just removed the 5px right margin on the "Sync map and table" toggle:
image

**Comment by jtquach1** [comment]
Got filters to intersect using CSS (visibility is affected by whether the Marker DOM elements exist):
working_filter_1
working_filter_2
working_filter_3

**Comment by jtquach1** [comment]
After combining map/table sync with visibility:
after_combining_visibility_and_sync

Ideas:
- have React rerender once after the initial render (visibility/sync depends on DOM elements, which wouldn't exist at the initial render)
- automatically toggle the sync checkbox (different from having it checked by default) so it will trigger a React rerender
- separate "visibility" for Markers and table, where Markers should only have the `invisible` className when the internal visibility is not `false`

**Comment by jtquach1** [comment]
Fixes:
- Having "Sync" checked on initial page load features all markers on map
- Table rows and Markers persist highlight when Markers split/merge on zoom change
### Before
#### Broken sync
before_fixed_sync

#### Broken highlight persisting
before_fixed_highlight

### After
after_sync_and_fixed_highlight
after_fixed_sync_2

**Review by Luke-Sikina — APPROVED** [review]

**Comment by jtquach1** [comment]
Last update:
after_sync_squashed_commits
- Table rows and Markers persist highlight upon splitting/merging
- Zoom change from zoom controls affect Marker visibility
- Map syncs to filtered table results by search query and Marker visibility when "Sync" checkbox is checked

**Pull request merged**
